services:

  map-service:
    build:
      context: ./map-service
      dockerfile: Dockerfile
    image: mcots/backend/map-service:latest
    container_name: map-service
    ports:
      - "${MAP_SERVICE_PORT:-8080}:${MAP_SERVICE_PORT:-8080}"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:${MONGODB_PORT:-27017}/${MONGODB_DB_NAME}
      - SERVER_PORT=${MAP_SERVICE_PORT:-8080}
      - FRONTEND_PORT=${FRONTEND_PORT:-5173}
      - INTELLIGENCE_SERVICE_PORT=${INTELLIGENCE_SERVICE_PORT:-8084}
      - MONGODB_PORT=${MONGODB_PORT:-27017}
      - MONGODB_HOST=${MONGODB_HOST:-mongodb}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb
      - auth-service
    networks:
      - mcots-backend-network

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    image: mcots/backend/auth-service:latest
    container_name: auth-service
    ports:
      - "${AUTH_SERVICE_PORT:-8081}:8081"
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=${MONGODB_PORT:-27017}
      - MONGODB_DB_NAME=${MONGODB_DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - SERVER_PORT=8081
    depends_on:
      - mongodb
    networks:
      - mcots-backend-network

  intelligence-service:
    build:
      context: ./intelligence-service
      dockerfile: Dockerfile
    image: mcots/backend/intelligence-service:latest
    container_name: intelligence-service
    ports:
      - "${INTELLIGENCE_SERVICE_PORT:-8084}:8084"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    networks:
      - mcots-backend-network
      
  mongodb:
    image: mongo:latest
    container_name: mcots-mongodb
    ports:
      - "${MONGODB_PORT:-27017}:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=${MONGODB_DB_NAME}
    networks:
      - mcots-backend-network

volumes:
  mongodb_data:

networks:
  mcots-backend-network:
    driver: bridge